---
driver_plugin: vagrant
platforms:
- name: centos-6.4-NAM
  driver_config:
    box: centos-6.4-NAM
    box_url: https://s3.amazonaws.com/despo/chef/centos64-provisionerless.box
    http_proxy: 
    https_proxy: 
suites:
- name: default
  run_list:
  - recipe[namtest]
  attributes: {}
